title = 'Arm Learning Paths'

baseURL = '/'
languageCode = 'en-us'
theme = "arm-design-system-hugo-theme"

enableGitInfo = true
enableRobotsTXT = true

[deployment]
[[deployment.targets]]
name = "internal-existing"
URL = "s3://armswdev.tk?region=us-east-1"
cloudFrontDistributionID = "E2VDQ2CYZATMO9"

[[deployment.targets]]
name = "internal"
URL = "s3://arm-learning-paths-internal?region=us-west-2"
cloudFrontDistributionID = "ENN4LK1IZUDIX"

[[deployment.targets]]
name = "production"
URL = "s3://arm-learning-paths?region=us-west-2"
cloudFrontDistributionID = "E2NEF61QWPFRIH"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[taxonomies]
subject = "subjects"
operatingsystem = "operatingsystems"
skilllevel = "skilllevels"
tool_software_language = "tools_software_languages"
armip = "armips"
cloud_service_provider = "cloud_service_providers"

[permalinks]
tools_software_languages = "/tag/:slug/"
operatingsystems = "/tag/:slug/"
subjects = "/tag/:slug/"
cloud_service_providers = "/tag/:slug/"
armips = "/tag/:slug/"

[related]
threshold = 0
includeNewer = true
toLower = false

[[related.indices]]
name = "cloud_service_providers"
weight = 100

[[related.indices]]
name = "tools_software_languages"
weight = 80

[[related.indices]]
name = "subjects"
weight = 50

[params]
# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/ArmDeveloperEcosystem/arm-learning-paths"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/ArmDeveloperEcosystem/arm-learning-paths"
# location of assets
assetsDir = "assets"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Uncomment this if your GitHub repo does not have "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
github_branch = "main"

# For metadata posting on socials
title = 'Arm Learning Paths'
description = 'Tutorials with code examples, created by the Arm ecosystem to develop better code faster across all platforms: Servers, phones, laptops, embedded devices, and microcontrollers.'
social_image = '/img/social-image.png'
twitter_handle = '@ArmSoftwareDev'
