# This is a basic workflow to help you get started with Actions

name: check-links

# Controls when the workflow will run
on:

  # run once a day at 6AM UTC
  schedule:
    - cron: '0 6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo Themes
          fetch-depth: 0 

      # Sets Up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: '0.98.0'
            extended: true
            
      # Post-CSS install
      - name: Install Post-CSS
        run: npm install postcss-cli

      # Builds arm-software-developer repo
      - name: Build
        run: hugo --minify

      - name: check html links
        # Don't fail the build on broken links
        continue-on-error: true
        uses: wjdp/htmltest-action@master
        with:
          # For consistency, use the same config file as for local builds
          config: .htmltest.yml
      - name: Archive htmltest results
        uses: actions/upload-artifact@v3
        # Note: Set ACTIONS_RUNTIME_TOKEN env variable to test with nektos/act
        with:
          name: htmltest-report
          path: tmp/.htmltest/htmltest.log
          retention-days: 7 # Default is 90 days

